targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - output: lib/pokemon.dart
              schema: lib/schema.gql
              queries_glob: lib/**.graphql
