name: provider_codegen
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  source_gen: ^0.9.5
  provider_annotation:
    path: ../provider_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner:

flutter:
